name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Caching emblem
        id: caching-emblem
        uses: actions/cache@v2
        with:
          path: |
            packages/pack1/dist
          key: ${{ runner.os }}-${{ hashFiles('packages/pack1/src/**') }}
      - name: Generate new emblem dist
        if: steps.caching-emblem.outputs.cache-hit != 'true'
        working-directory: packages/pack1/
        run: |
          npm install
          npm run build